apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-vol-lcl
  annotations:
    volume.beta.kubernetes.io/storage-class: lclstg
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
